/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Geist, Geist_Mono, Imprima } from "next/font/google";
import "./globals.css";
import Providers from "./components/providers";
import "bootstrap/dist/css/bootstrap.min.css";
import Navigation from "./components/Navigation";
import { AuthProvider } from "./context/AuthContext";
import Footer from "./components/footer"
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MEDIVO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        strategy="afterInteractive"
      />
        {" "}
       
            <AuthProvider>
          <Providers>
            <Navigation/>
            {children}
     
          </Providers>
        </AuthProvider>
      
    
        
        
      </body>
      
    </html>
  );
}
